"""Embed web/portal.html into include/web_assets.h before every build.

PlatformIO runs this via ``extra_scripts``; it is also runnable by hand:

    python tools/build_web_assets.py

The page is stored as a PROGMEM string literal, which keeps it out of RAM and
lets ``WebServer::send_P`` stream it straight from flash.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "web" / "portal.html"
TARGET = ROOT / "include" / "web_assets.h"
DELIMITER = "PORTAL"

HEADER = """// Generated by tools/build_web_assets.py — do not edit.
// Source: web/portal.html

#pragma once

#include <pgmspace.h>

const char PORTAL_HTML[] PROGMEM = R"{delim}(
{html}){delim}";
"""


def build() -> int:
    html = SOURCE.read_text(encoding="utf-8")

    # A raw string literal ends at the delimiter, so the page must not contain it.
    if f'){DELIMITER}"' in html:
        print(f"error: {SOURCE} contains the raw-string delimiter ){DELIMITER}\"", file=sys.stderr)
        return 1

    generated = HEADER.format(delim=DELIMITER, html=html)
    if TARGET.exists() and TARGET.read_text(encoding="utf-8") == generated:
        return 0  # unchanged, keep the timestamp so the build does not redo work

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated, encoding="utf-8")
    print(f"web assets: {len(html)} bytes -> {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__" or "SCons" in str(globals().get("__name__", "")):
    status = build()
    if status:
        raise SystemExit(status)
